# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: loose_api_development
  pool: 5
  username: loose_api
  password: password1

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: loose_api_test
  pool: 5
  username: loose_api
  password: password1

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: loose_api_production
  pool: 5
  username: loose_api
  password: password1
